package isilimageprocessing;

import CImage.*;
import CImage.Exceptions.*;
import CImage.Observers.*;
import CImage.Observers.Events.*;
import ImageProcessing.Complexe.MatriceComplexe;
import ImageProcessing.Contours.ContoursLineaire;
import ImageProcessing.Contours.ContoursNonLineaire;
import ImageProcessing.Fourier.Fourier;
import ImageProcessing.Histogramme.Histogramme;
import ImageProcessing.Linear.FiltrageLineaireLocal;
import ImageProcessing.Linear.GlobalLinearFiltering;
import ImageProcessing.Linear.LocalLinearFiltering;
import ImageProcessing.NonLineaire.MorphoComplexe;
import ImageProcessing.NonLineaire.MorphoElementaire;
import ImageProcessing.Seuillage.Seuillage;
import isilimageprocessing.Dialogues.*;
import java.awt.*;
import java.io.*;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author  HP_Propri�taire
 */
public class IsilImageProcessing extends javax.swing.JFrame implements ClicListener,SelectLigneListener,SelectRectListener,SelectRectFillListener,SelectCercleListener,SelectCercleFillListener 
{
    private CImageRGB imageRGB;
    private CImageNG  imageNG;
    
    private JLabelBeanCImage observer;
    private Color couleurPinceauRGB;
    private int   couleurPinceauNG;
    
    /** Creates new form TestCImage2 */
    public IsilImageProcessing() 
    {
        initComponents();
        
        imageRGB = null;
        imageNG  = null;
        
        observer = new JLabelBeanCImage();
        observer.addClicListener(this);
        observer.addSelectLigneListener(this);
        observer.addSelectRectListener(this);
        observer.addSelectRectFillListener(this);
        observer.addSelectCercleListener(this);
        observer.addSelectCercleFillListener(this);
        observer.setMode(JLabelBeanCImage.INACTIF);
        jScrollPane.setViewportView(observer);
        
        jMenuDessiner.setEnabled(false);
        jMenuFourier.setEnabled(false);
        jMenuHistogramme.setEnabled(false);
        
        couleurPinceauRGB = Color.BLACK;
        couleurPinceauNG = 0;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDessiner = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuImage = new javax.swing.JMenu();
        jMenuNouvelle = new javax.swing.JMenu();
        jMenuItemNouvelleRGB = new javax.swing.JMenuItem();
        jMenuItemNouvelleNG = new javax.swing.JMenuItem();
        jMenuOuvrir = new javax.swing.JMenu();
        jMenuItemOuvrirRGB = new javax.swing.JMenuItem();
        jMenuItemOuvrirNG = new javax.swing.JMenuItem();
        jMenuItemEnregistrerSous = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuQuitter = new javax.swing.JMenuItem();
        jMenuDessiner = new javax.swing.JMenu();
        jMenuItemCouleurPinceau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBoxMenuItemDessinerPixel = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerLigne = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerRectangle = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerRectanglePlein = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerCercle = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerCerclePlein = new javax.swing.JCheckBoxMenuItem();
        jMenuFourier = new javax.swing.JMenu();
        jMenuFourierAfficher = new javax.swing.JMenu();
        jMenuItemFourierAfficherModule = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPhase = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPartieReelle = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPartieImaginaire = new javax.swing.JMenuItem();
        jMenuHistogramme = new javax.swing.JMenu();
        jMenuHistogrammeAfficher = new javax.swing.JMenuItem();
        AfficheItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        SaturationItem = new javax.swing.JMenuItem();
        GammaItem = new javax.swing.JMenuItem();
        EgalisationItem = new javax.swing.JMenuItem();
        NegatifItem = new javax.swing.JMenuItem();
        jMenuLinearFiltering = new javax.swing.JMenu();
        jMenuGlobal = new javax.swing.JMenu();
        jMenuItemIdealLowPassFilter = new javax.swing.JMenuItem();
        jMenuItemIdealHighPassFilter = new javax.swing.JMenuItem();
        jMenuItemLowPassButterworthFilter = new javax.swing.JMenuItem();
        jMenuItemHighPassButterworthFilter = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MoyenneurItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        ErosionItem = new javax.swing.JMenuItem();
        DilatationItem = new javax.swing.JMenuItem();
        OuvertureItem = new javax.swing.JMenuItem();
        FermetureItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        DilGeoItem = new javax.swing.JMenuItem();
        RecGeoItem = new javax.swing.JMenuItem();
        MedItem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        PrewittItem = new javax.swing.JMenuItem();
        SobelItem = new javax.swing.JMenuItem();
        Laplace4ITem = new javax.swing.JMenuItem();
        Laplace8Item = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        gEroItem = new javax.swing.JMenuItem();
        gDilItem = new javax.swing.JMenuItem();
        gBeuItem = new javax.swing.JMenuItem();
        LNLItem = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        SeuillageItem = new javax.swing.JMenuItem();
        SeuilAutoItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Isil Image Processing");

        jMenuImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Net 13_p1.jpg"))); // NOI18N
        jMenuImage.setText("Image");

        jMenuNouvelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/File 65_p3.jpg"))); // NOI18N
        jMenuNouvelle.setText("Nouvelle");

        jMenuItemNouvelleRGB.setText("Image RGB");
        jMenuItemNouvelleRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNouvelleRGBActionPerformed(evt);
            }
        });
        jMenuNouvelle.add(jMenuItemNouvelleRGB);

        jMenuItemNouvelleNG.setText("Image NG");
        jMenuItemNouvelleNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNouvelleNGActionPerformed(evt);
            }
        });
        jMenuNouvelle.add(jMenuItemNouvelleNG);

        jMenuImage.add(jMenuNouvelle);

        jMenuOuvrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Folder 036_p3.jpg"))); // NOI18N
        jMenuOuvrir.setText("Ouvrir");

        jMenuItemOuvrirRGB.setText("Image RGB");
        jMenuItemOuvrirRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirRGBActionPerformed(evt);
            }
        });
        jMenuOuvrir.add(jMenuItemOuvrirRGB);

        jMenuItemOuvrirNG.setText("Image NG");
        jMenuItemOuvrirNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirNGActionPerformed(evt);
            }
        });
        jMenuOuvrir.add(jMenuItemOuvrirNG);

        jMenuImage.add(jMenuOuvrir);

        jMenuItemEnregistrerSous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/DD 27_p3.jpg"))); // NOI18N
        jMenuItemEnregistrerSous.setText("Enregistrer sous...");
        jMenuItemEnregistrerSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnregistrerSousActionPerformed(evt);
            }
        });
        jMenuImage.add(jMenuItemEnregistrerSous);
        jMenuImage.add(jSeparator1);

        jMenuQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP 59_p3.jpg"))); // NOI18N
        jMenuQuitter.setText("Quitter");
        jMenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitterActionPerformed(evt);
            }
        });
        jMenuImage.add(jMenuQuitter);

        jMenuBar1.add(jMenuImage);

        jMenuDessiner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Display 28_p1.jpg"))); // NOI18N
        jMenuDessiner.setText("Dessiner");

        jMenuItemCouleurPinceau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Display 14_p3.jpg"))); // NOI18N
        jMenuItemCouleurPinceau.setText("Couleur");
        jMenuItemCouleurPinceau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCouleurPinceauActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jMenuItemCouleurPinceau);
        jMenuDessiner.add(jSeparator2);

        jCheckBoxMenuItemDessinerPixel.setText("Pixel");
        jCheckBoxMenuItemDessinerPixel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerPixelActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerPixel);

        jCheckBoxMenuItemDessinerLigne.setText("Ligne");
        jCheckBoxMenuItemDessinerLigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerLigneActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerLigne);

        jCheckBoxMenuItemDessinerRectangle.setText("Rectangle");
        jCheckBoxMenuItemDessinerRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerRectangleActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerRectangle);

        jCheckBoxMenuItemDessinerRectanglePlein.setText("Rectangle plein");
        jCheckBoxMenuItemDessinerRectanglePlein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerRectanglePleinActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerRectanglePlein);

        jCheckBoxMenuItemDessinerCercle.setText("Cercle");
        jCheckBoxMenuItemDessinerCercle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerCercleActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerCercle);

        jCheckBoxMenuItemDessinerCerclePlein.setText("Cercle plein");
        jCheckBoxMenuItemDessinerCerclePlein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerCerclePleinActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerCerclePlein);

        jMenuBar1.add(jMenuDessiner);

        jMenuFourier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP 51_p1.jpg"))); // NOI18N
        jMenuFourier.setText("Fourier");

        jMenuFourierAfficher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP 51_p3.jpg"))); // NOI18N
        jMenuFourierAfficher.setText("Afficher");

        jMenuItemFourierAfficherModule.setText("Module");
        jMenuItemFourierAfficherModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherModuleActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherModule);

        jMenuItemFourierAfficherPhase.setText("Phase");
        jMenuItemFourierAfficherPhase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPhaseActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPhase);

        jMenuItemFourierAfficherPartieReelle.setText("Partie Reelle");
        jMenuItemFourierAfficherPartieReelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPartieReelleActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPartieReelle);

        jMenuItemFourierAfficherPartieImaginaire.setText("Partie Imaginaire");
        jMenuItemFourierAfficherPartieImaginaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPartieImaginaireActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPartieImaginaire);

        jMenuFourier.add(jMenuFourierAfficher);

        jMenuBar1.add(jMenuFourier);

        jMenuHistogramme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/report_48_hot.jpg"))); // NOI18N
        jMenuHistogramme.setText("Histogramme");

        jMenuHistogrammeAfficher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/report_32_hot.jpg"))); // NOI18N
        jMenuHistogrammeAfficher.setText("Afficher");
        jMenuHistogrammeAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistogrammeAfficherActionPerformed(evt);
            }
        });
        jMenuHistogramme.add(jMenuHistogrammeAfficher);

        AfficheItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Display 14_p3.jpg"))); // NOI18N
        AfficheItem2.setText("Afficher les paramètres de l'image");
        AfficheItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficheItem2ActionPerformed(evt);
            }
        });
        jMenuHistogramme.add(AfficheItem2);

        jMenu5.setText("Transformation Lineaire");

        SaturationItem.setText("Lineaires avec saturation");
        SaturationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaturationItemActionPerformed(evt);
            }
        });
        jMenu5.add(SaturationItem);

        GammaItem.setText("Gamma");
        GammaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GammaItemActionPerformed(evt);
            }
        });
        jMenu5.add(GammaItem);

        EgalisationItem.setText("Egalisation");
        EgalisationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EgalisationItemActionPerformed(evt);
            }
        });
        jMenu5.add(EgalisationItem);

        NegatifItem.setText("Negatif");
        NegatifItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegatifItemActionPerformed(evt);
            }
        });
        jMenu5.add(NegatifItem);

        jMenuHistogramme.add(jMenu5);

        jMenuBar1.add(jMenuHistogramme);

        jMenuLinearFiltering.setText("Linear Filtering");

        jMenuGlobal.setText("Global");

        jMenuItemIdealLowPassFilter.setText("Ideal low-pass filter");
        jMenuItemIdealLowPassFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIdealLowPassFilterActionPerformed(evt);
            }
        });
        jMenuGlobal.add(jMenuItemIdealLowPassFilter);

        jMenuItemIdealHighPassFilter.setText("Ideal high-pass filter");
        jMenuItemIdealHighPassFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIdealHighPassFilterActionPerformed(evt);
            }
        });
        jMenuGlobal.add(jMenuItemIdealHighPassFilter);

        jMenuItemLowPassButterworthFilter.setText("Low-pass Butterworth filter");
        jMenuItemLowPassButterworthFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLowPassButterworthFilterActionPerformed(evt);
            }
        });
        jMenuGlobal.add(jMenuItemLowPassButterworthFilter);

        jMenuItemHighPassButterworthFilter.setText("High-pass Butterworth filter");
        jMenuItemHighPassButterworthFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHighPassButterworthFilterActionPerformed(evt);
            }
        });
        jMenuGlobal.add(jMenuItemHighPassButterworthFilter);

        jMenuLinearFiltering.add(jMenuGlobal);

        jMenu1.setText("Local");

        jMenuItem2.setText("Masque de convolution");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        MoyenneurItem.setText("Moyenneur");
        MoyenneurItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoyenneurItemActionPerformed(evt);
            }
        });
        jMenu1.add(MoyenneurItem);

        jMenuLinearFiltering.add(jMenu1);

        jMenuBar1.add(jMenuLinearFiltering);

        jMenu2.setText("Traitement Non-linéaire");

        jMenu3.setText("Elementaire");

        ErosionItem.setText("Erosion");
        ErosionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErosionItemActionPerformed(evt);
            }
        });
        jMenu3.add(ErosionItem);

        DilatationItem.setText("Dilatation");
        DilatationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DilatationItemActionPerformed(evt);
            }
        });
        jMenu3.add(DilatationItem);

        OuvertureItem.setText("Ouverture");
        OuvertureItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OuvertureItemActionPerformed(evt);
            }
        });
        jMenu3.add(OuvertureItem);

        FermetureItem.setText("Fermeture");
        FermetureItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermetureItemActionPerformed(evt);
            }
        });
        jMenu3.add(FermetureItem);

        jMenu2.add(jMenu3);

        jMenu4.setText("Complexe");

        DilGeoItem.setText("Dilatation Geodesique");
        DilGeoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DilGeoItemActionPerformed(evt);
            }
        });
        jMenu4.add(DilGeoItem);

        RecGeoItem.setText("Reconstruction Geodesique");
        RecGeoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecGeoItemActionPerformed(evt);
            }
        });
        jMenu4.add(RecGeoItem);

        MedItem.setText("Filtre Median");
        MedItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedItemActionPerformed(evt);
            }
        });
        jMenu4.add(MedItem);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Contours");

        jMenu7.setText("Lineaire");

        PrewittItem.setText("Prewitt");
        PrewittItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrewittItemActionPerformed(evt);
            }
        });
        jMenu7.add(PrewittItem);

        SobelItem.setText("Sobel");
        SobelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobelItemActionPerformed(evt);
            }
        });
        jMenu7.add(SobelItem);

        Laplace4ITem.setText("Laplace 4");
        Laplace4ITem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Laplace4ITemActionPerformed(evt);
            }
        });
        jMenu7.add(Laplace4ITem);

        Laplace8Item.setText("Laplace 8");
        Laplace8Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Laplace8ItemActionPerformed(evt);
            }
        });
        jMenu7.add(Laplace8Item);

        jMenu6.add(jMenu7);

        jMenu8.setText("Non-Lineaire");

        gEroItem.setText("gradient Erosion");
        gEroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gEroItemActionPerformed(evt);
            }
        });
        jMenu8.add(gEroItem);

        gDilItem.setText("gradient Dilatation");
        gDilItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gDilItemActionPerformed(evt);
            }
        });
        jMenu8.add(gDilItem);

        gBeuItem.setText("gradient Beucher");
        gBeuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBeuItemActionPerformed(evt);
            }
        });
        jMenu8.add(gBeuItem);

        LNLItem.setText("Laplacien Non Lineaire");
        LNLItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNLItemActionPerformed(evt);
            }
        });
        jMenu8.add(LNLItem);

        jMenu6.add(jMenu8);

        jMenuBar1.add(jMenu6);

        jMenu9.setText("Seuillage");

        SeuillageItem.setText("Simple");
        SeuillageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeuillageItemActionPerformed(evt);
            }
        });
        jMenu9.add(SeuillageItem);

        SeuilAutoItem.setText("Automatique");
        SeuilAutoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeuilAutoItemActionPerformed(evt);
            }
        });
        jMenu9.add(SeuilAutoItem);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(973, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHistogrammeAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistogrammeAfficherActionPerformed
        int histo[];
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }
        
        // Cr�ation du dataset
        XYSeries serie = new XYSeries("Histo");
        for(int i=0 ; i<256 ; i++) serie.add(i,histo[i]);
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(serie);
        
        // Creation du chart
        JFreeChart chart = ChartFactory.createHistogram("Histogramme","Niveaux de gris","Nombre de pixels",dataset,PlotOrientation.VERTICAL,false,false,false);

        XYPlot plot = (XYPlot)chart.getXYPlot();
        ValueAxis axeX = plot.getDomainAxis();
        axeX.setRange(0,255);
        plot.setDomainAxis(axeX);
        
        // creation d'une frame
        ChartFrame frame = new ChartFrame("Histogramme de l'image",chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuHistogrammeAfficherActionPerformed

    private void activeMenusNG()
    {
        jMenuDessiner.setEnabled(true);
        jMenuFourier.setEnabled(true);
        jMenuHistogramme.setEnabled(true);
    }
    
    private void activeMenusRGB()
    {
        jMenuDessiner.setEnabled(true);
        jMenuFourier.setEnabled(false);
        jMenuHistogramme.setEnabled(false);
    }
    
    private void jCheckBoxMenuItemDessinerCerclePleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerCerclePleinActionPerformed
        if (!jCheckBoxMenuItemDessinerCerclePlein.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(true);
            observer.setMode(JLabelBeanCImage.SELECT_CERCLE_FILL);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerCerclePleinActionPerformed

    private void jCheckBoxMenuItemDessinerCercleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerCercleActionPerformed
        if (!jCheckBoxMenuItemDessinerCercle.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(true);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_CERCLE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerCercleActionPerformed

    private void jMenuItemFourierAfficherPartieImaginaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPartieImaginaireActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double partieImaginaire[][] = fourier.getPartieImaginaire();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,partieImaginaire,"Fourier : Affichage de la partie imaginaire");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFourierAfficherPartieImaginaireActionPerformed

    private void jMenuItemFourierAfficherPartieReelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPartieReelleActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double partieReelle[][] = fourier.getPartieReelle();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,partieReelle,"Fourier : Affichage de la partie reelle");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }

    }//GEN-LAST:event_jMenuItemFourierAfficherPartieReelleActionPerformed

    private void jMenuItemFourierAfficherPhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPhaseActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double phase[][] = fourier.getPhase();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,phase,"Fourier : Affichage de la phase");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }

    }//GEN-LAST:event_jMenuItemFourierAfficherPhaseActionPerformed

    private void jMenuItemFourierAfficherModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherModuleActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double module[][] = fourier.getModule();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,module,"Fourier : Affichage du module");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFourierAfficherModuleActionPerformed

    private void jCheckBoxMenuItemDessinerPixelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerPixelActionPerformed
        if (!jCheckBoxMenuItemDessinerPixel.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(true);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.CLIC);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerPixelActionPerformed

    private void jMenuItemEnregistrerSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnregistrerSousActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    if (imageRGB != null) imageRGB.enregistreFormatPNG(fichier);
                    if (imageNG != null) imageNG.enregistreFormatPNG(fichier);
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemEnregistrerSousActionPerformed

    private void jMenuItemOuvrirNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirNGActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    imageNG = new CImageNG(fichier);
                    observer.setCImage(imageNG);
                    imageRGB = null;
                    activeMenusNG();
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemOuvrirNGActionPerformed

    private void jMenuItemNouvelleNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNouvelleNGActionPerformed
        JDialogNouvelleCImageNG dialog = new JDialogNouvelleCImageNG(this,true);
        dialog.setVisible(true);
        imageNG = dialog.getCImageNG();
        observer.setCImage(imageNG);
        imageRGB = null;
        activeMenusNG();
    }//GEN-LAST:event_jMenuItemNouvelleNGActionPerformed

    private void jMenuItemCouleurPinceauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCouleurPinceauActionPerformed
        if (imageRGB != null)
        {
            Color newC = JColorChooser.showDialog(this,"Couleur du pinceau",couleurPinceauRGB);
            if (newC != null) couleurPinceauRGB = newC;
            observer.setCouleurPinceau(couleurPinceauRGB);
        }
        
        if (imageNG != null)
        {
            JDialogChoixCouleurNG dialog = new JDialogChoixCouleurNG(this,true,couleurPinceauNG);
            dialog.setVisible(true);
            couleurPinceauNG = dialog.getCouleur();
        }
    }//GEN-LAST:event_jMenuItemCouleurPinceauActionPerformed

    private void jCheckBoxMenuItemDessinerRectanglePleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerRectanglePleinActionPerformed
        if (!jCheckBoxMenuItemDessinerRectanglePlein.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(true);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_RECT_FILL);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerRectanglePleinActionPerformed

    private void jCheckBoxMenuItemDessinerRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerRectangleActionPerformed
        if (!jCheckBoxMenuItemDessinerRectangle.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(true);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_RECT);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerRectangleActionPerformed

    private void jCheckBoxMenuItemDessinerLigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerLigneActionPerformed
        if (!jCheckBoxMenuItemDessinerLigne.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(true);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_LIGNE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerLigneActionPerformed

    private void jMenuItemNouvelleRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNouvelleRGBActionPerformed
        JDialogNouvelleCImageRGB dialog = new JDialogNouvelleCImageRGB(this,true);
        dialog.setVisible(true);
        imageRGB = dialog.getCImageRGB();
        observer.setCImage(imageRGB);
        imageNG = null;
        activeMenusRGB();
    }//GEN-LAST:event_jMenuItemNouvelleRGBActionPerformed

    private void jMenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitterActionPerformed

    private void jMenuItemOuvrirRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirRGBActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    imageRGB = new CImageRGB(fichier);
                    observer.setCImage(imageRGB);
                    imageNG = null;
                    activeMenusRGB();
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemOuvrirRGBActionPerformed

    private void jMenuItemIdealLowPassFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIdealLowPassFilterActionPerformed
        // TODO add your handling code here:
        
        if (imageNG == null) {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE); // https://mkyong.com/swing/java-swing-how-to-make-a-simple-dialog/
            return;
        }

        try {
            String input = JOptionPane.showInputDialog(this, "Enter cutoff frequency:");
            if (input != null && !input.isEmpty()) {
                int cutoffFrequency = Integer.parseInt(input);
                int[][] mat = imageNG.getMatrice();  // image to int matrix
                int[][] filteredImage = GlobalLinearFiltering.idealLowPassFilter(mat, cutoffFrequency);
                imageNG.setMatrice(filteredImage);
                observer.setCImage(imageNG);      // update image ?
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid frequency entered.", "Error", JOptionPane.ERROR_MESSAGE); // String to numeric
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error applying filter: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemIdealLowPassFilterActionPerformed

    private void jMenuItemIdealHighPassFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIdealHighPassFilterActionPerformed
        // TODO add your handling code here:

        if (imageNG == null) {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE); // https://mkyong.com/swing/java-swing-how-to-make-a-simple-dialog/
            return;
        }

        try {
            String input = JOptionPane.showInputDialog(this, "Enter cutoff frequency:");
            if (input != null && !input.isEmpty()) {
                int cutoffFrequency = Integer.parseInt(input);
                int[][] mat = imageNG.getMatrice(); // image to int matrix
                int[][] filteredImage = GlobalLinearFiltering.idealHighPassFilter(mat, cutoffFrequency);
                imageNG.setMatrice(filteredImage);
                observer.setCImage(imageNG); // upadted image
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid frequency entered.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error applying filter: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemIdealHighPassFilterActionPerformed

    private void jMenuItemLowPassButterworthFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLowPassButterworthFilterActionPerformed
        // TODO add your handling code here:
        
        if (imageNG == null) {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField cutoffField = new JTextField(5);
        JTextField orderField = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Cutoff frequency:"));
        myPanel.add(cutoffField);
        myPanel.add(Box.createHorizontalStrut(15)); // separate
        myPanel.add(new JLabel("Order:"));
        myPanel.add(orderField);
//        myPanel.add(new JLabel("Enter cutoff frequency and order:"));

        try {
            int confirmChoice = JOptionPane.showConfirmDialog(this, myPanel, "Enter cutoff frequency and order:", JOptionPane.OK_CANCEL_OPTION);
            if (confirmChoice == JOptionPane.OK_OPTION) {
                int cutoffFrequency = Integer.parseInt(cutoffField.getText());
                int order = Integer.parseInt(orderField.getText());
                
                int[][] mat = imageNG.getMatrice(); // image to int matrix
                int[][] filteredImage = GlobalLinearFiltering.lowPassButterworthFilter(mat, cutoffFrequency, order);
                imageNG.setMatrice(filteredImage);
                observer.setCImage(imageNG);
            }
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid frequency entered.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error applying filter: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemLowPassButterworthFilterActionPerformed

    private void jMenuItemHighPassButterworthFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHighPassButterworthFilterActionPerformed
        // TODO add your handling code here:
        
        if (imageNG == null) {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField cutoffField = new JTextField(5);
        JTextField orderField = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Cutoff frequency:"));
        myPanel.add(cutoffField);
        myPanel.add(Box.createHorizontalStrut(15)); // separate
        myPanel.add(new JLabel("Order:"));
        myPanel.add(orderField);

        try {
            int confirmChoice = JOptionPane.showConfirmDialog(this, myPanel, "Enter cutoff frequency and order:", JOptionPane.OK_CANCEL_OPTION);
            if (confirmChoice == JOptionPane.OK_OPTION) {
                int cutoffFrequency = Integer.parseInt(cutoffField.getText());
                int order = Integer.parseInt(orderField.getText());
                
                int[][] mat = imageNG.getMatrice(); // image to int matrix
                int[][] filteredImage = GlobalLinearFiltering.highPassButterworthFilter(mat, cutoffFrequency, order);
                imageNG.setMatrice(filteredImage);
                observer.setCImage(imageNG);
            }
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid frequency entered.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error applying filter: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemHighPassButterworthFilterActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField masqueTail = new JTextField(5);
        JTextField masqueText = new JTextField(25);
        
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Tails du masque:"));
        masquePanel.add(masqueTail);
        masquePanel.add(Box.createHorizontalStrut(15)); // separate
        masquePanel.add(new JLabel("le masque en lui même \n(;->nouvelle ligne \n,-> nouveau élément)"));
        masquePanel.add(masqueText);
        
        try
        {
         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
            if (confirmChoice == JOptionPane.OK_OPTION) 
            {
                int tail = Integer.parseInt(masqueTail.getText());
                if(tail % 2 == 0)
                {
                    throw new NumberFormatException("Tail n'est pas impaire");
                }
                
                //Lecture du masque
                String[] masqueLignes = masqueText.getText().split(";");
                double[][] masque = new double[masqueLignes.length][masqueLignes.length];
                double sumMasque = 0;
                for (int u = 0; u < masqueLignes.length; u++)
                {
                    for (int v = 0; v < masqueLignes.length; v++) 
                    {
                        masque[u][v] = Double.parseDouble(masqueLignes[v].split(",")[u]);
                        sumMasque += masque[u][v];
                    }
                }
                
                if(sumMasque > 1 )
                {
                    throw new Exception("La somme du masque doit être équale à un");
                }
                
                int[][] imgFiltrer = FiltrageLineaireLocal.filtreMasqueConvolution(imageNG.getMatrice(),masque);
//                int[][] imgFiltrer = LocalLinearFiltering.convolutionMaskFilter(imageNG.getMatrice(),masque);

                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
            }
        } 
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (ArrayIndexOutOfBoundsException oe)
        {
            JOptionPane.showMessageDialog(this, "Le format du masque est incorrect", "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MoyenneurItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoyenneurItemActionPerformed
        if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField masqueTail = new JTextField(5);
        
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Tails du masque:"));
        masquePanel.add(masqueTail);
        
        try
        {
         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
            {
                int tail = Integer.parseInt(masqueTail.getText());
                if(tail % 2 == 0)
                {
                    throw new NumberFormatException("Tail n'est pas impaire");
                }
                
                int[][] imgFiltrer = FiltrageLineaireLocal.filtreMoyenneur(imageNG.getMatrice(),tail);
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_MoyenneurItemActionPerformed

    private void DilatationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DilatationItemActionPerformed
       if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField masqueTail = new JTextField(5);
        
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Tails du masque:"));
        masquePanel.add(masqueTail);
        
        try
        {
         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
            {
                int tail = Integer.parseInt(masqueTail.getText());
                if(tail % 2 == 0)
                {
                    throw new NumberFormatException("Tail n'est pas impaire");
                }
                
                int[][] imgFiltrer = MorphoElementaire.dilatation(imageNG.getMatrice(),tail);
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DilatationItemActionPerformed

    private void ErosionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErosionItemActionPerformed
       if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField masqueTail = new JTextField(5);
        
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Tails du masque:"));
        masquePanel.add(masqueTail);
        
        try
        {
         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
            {
                int tail = Integer.parseInt(masqueTail.getText());
                if(tail % 2 == 0)
                {
                    throw new NumberFormatException("Tail n'est pas impaire");
                }
                
                int[][] imgFiltrer = MorphoElementaire.erosion(imageNG.getMatrice(),tail);
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ErosionItemActionPerformed

    private void OuvertureItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OuvertureItemActionPerformed
      if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField masqueTail = new JTextField(5);
        
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Tails du masque:"));
        masquePanel.add(masqueTail);
        
        try
        {
         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
            {
                int tail = Integer.parseInt(masqueTail.getText());
                if(tail % 2 == 0)
                {
                    throw new NumberFormatException("Tail n'est pas impaire");
                }
                
                int[][] imgFiltrer = MorphoElementaire.ouverture(imageNG.getMatrice(),tail);
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_OuvertureItemActionPerformed

    private void FermetureItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermetureItemActionPerformed
    if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField masqueTail = new JTextField(5);
        
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Tails du masque:"));
        masquePanel.add(masqueTail);
        
        
        try
        {
         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
            {
                int tail = Integer.parseInt(masqueTail.getText());
                if(tail % 2 == 0)
                {
                    throw new NumberFormatException("Tail n'est pas impaire");
                }
                
                int[][] imgFiltrer = MorphoElementaire.fermeture(imageNG.getMatrice(),tail);
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FermetureItemActionPerformed

    private void DilGeoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DilGeoItemActionPerformed
        
        if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Choisis un masque
        try{
            CImageNG  masqueGeo = new CImageNG(new int[1][1]);
            JFileChooser choix = new JFileChooser();
            File fichier;

            choix.setCurrentDirectory(new File ("."));
            if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
            {
                fichier = choix.getSelectedFile();
                if (fichier != null)
                {
                    try 
                    {
                        masqueGeo = new CImageNG(fichier);
                    } 
                    catch (IOException ex) 
                    {
                        System.err.println("Erreur I/O : " + ex.getMessage());
                        return;
                    }
                }  
            }else
            {
                return;
            }

            JTextField iterField = new JTextField(5);
            JTextField tailField = new JTextField(5);
            JPanel masquePanel = new JPanel();
            masquePanel.add(new JLabel("Nombre d'itération:"));
            masquePanel.add(iterField);
            masquePanel.add(Box.createHorizontalStrut(15)); // separate
            masquePanel.add(new JLabel("Tail de l'élément structurant :"));
            masquePanel.add(tailField);

             int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
             if (confirmChoice == JOptionPane.OK_OPTION) 
             {
                int iter = Integer.parseInt(iterField.getText());  
                int tail = Integer.parseInt(tailField.getText()); 
                int[][] imgFiltrer = MorphoComplexe.dilatationGeodesique(imageNG.getMatrice(),masqueGeo.getMatrice(),iter,tail);
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
             }
        }catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }      
    }//GEN-LAST:event_DilGeoItemActionPerformed

    private void RecGeoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecGeoItemActionPerformed
          
        if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Choisis un masque
        try{
            CImageNG  masqueGeo = new CImageNG(new int[1][1]);
            JFileChooser choix = new JFileChooser();
            File fichier;

            choix.setCurrentDirectory(new File ("."));
            if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
            {
                fichier = choix.getSelectedFile();
                if (fichier != null)
                {
                    try 
                    {
                        masqueGeo = new CImageNG(fichier);
                    } 
                    catch (IOException ex) 
                    {
                        System.err.println("Erreur I/O : " + ex.getMessage());
                        return;
                    }
                }  
            }else
            {
                return;
            }

            JTextField tailField = new JTextField(5);
            JPanel masquePanel = new JPanel();
            masquePanel.add(new JLabel("Tail de l'élément structurant :"));
            masquePanel.add(tailField);
            
             int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
             if (confirmChoice == JOptionPane.OK_OPTION) 
             {
                int tail = Integer.parseInt(tailField.getText());  
                int[][] imgFiltrer = MorphoComplexe.reconstructionGeodesique(imageNG.getMatrice(),masqueGeo.getMatrice(), tail);
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
             }
        }catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_RecGeoItemActionPerformed

    private void MedItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedItemActionPerformed
        if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JTextField masqueTail = new JTextField(5);
        
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Tails du masque:"));
        masquePanel.add(masqueTail);
        
        try
        {
         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
            {
                int tail = Integer.parseInt(masqueTail.getText());
                if(tail % 2 == 0)
                {
                    throw new NumberFormatException("Tail n'est pas impaire");
                }
                
                int[][] imgFiltrer = MorphoComplexe.filtreMedian(imageNG.getMatrice(),tail);
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MedItemActionPerformed

    private void AfficheItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficheItem2ActionPerformed
      if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("MAX :"+Histogramme.maximum(imageNG.getMatrice())));
        masquePanel.add(new JLabel("MIN :"+Histogramme.minimum(imageNG.getMatrice())));
        masquePanel.add(new JLabel("LUM :"+Histogramme.luminance(imageNG.getMatrice())));
        masquePanel.add(new JLabel("CONTRASTE 1 :"+Histogramme.contraste1(imageNG.getMatrice())));
        masquePanel.add(new JLabel("CONTRASTE 2 :"+Histogramme.contraste2(imageNG.getMatrice())));
        JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
        
        }catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);  
        }
        
        
    }//GEN-LAST:event_AfficheItem2ActionPerformed

    private void EgalisationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EgalisationItemActionPerformed
       int[] histo;
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }

        MakeHisto(histo,"Avant Egalisation","Avant Egalisation");
        try{
        int[][] imgFiltrer = Histogramme.rehaussement(imageNG.getMatrice(), Histogramme.creeCourbeTonaleEgalisation(imageNG.getMatrice()));
        imageNG.setMatrice(imgFiltrer);
        observer.setCImage(imageNG);
        System.out.println("end");
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }
        MakeHisto(histo,"Avec Egalisation","Avec Egalisation");
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);   
        }
             
    }//GEN-LAST:event_EgalisationItemActionPerformed

    private void SaturationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaturationItemActionPerformed
        int histo[];
        
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }
        MakeHisto(histo,"Avant Saturation","Avant Saturation");
        
        JTextField minField = new JTextField(5);
        JTextField maxField = new JTextField(5);
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("min saturation :")); 
        masquePanel.add(minField);
        masquePanel.add(Box.createHorizontalStrut(15)); 
        masquePanel.add(new JLabel("max saturation :")); 
        masquePanel.add(maxField);
   
        int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
        if (confirmChoice == JOptionPane.OK_OPTION) 
             {
                try{
                 int min=Integer.parseInt(minField.getText());
                 int max =Integer.parseInt(maxField.getText()); 
                int[][] imgFiltrer = Histogramme.rehaussement(imageNG.getMatrice(), Histogramme.creeCourbeTonaleLineaireSaturation(min, max));
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
                try 
                {
                    int f_int[][] = imageNG.getMatrice();
                    histo = Histogramme.Histogramme256(f_int);
                } 
                catch (CImageNGException ex) 
                {
                    System.out.println("Erreur CImageNG : " + ex.getMessage());
                    return;
                }
                MakeHisto(histo,"Avec Saturation","Avec Saturation");
                }
                catch(Exception e)
                {
                 JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);   
                }
             }  
    }//GEN-LAST:event_SaturationItemActionPerformed
    
    private void GammaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GammaItemActionPerformed
      
        int[] histo;
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }
        MakeHisto(histo,"Avant Gamme","Avant Gamme");
        
        JTextField gammaField = new JTextField(5);
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("gamme :")); 
        masquePanel.add(gammaField); 
   
        int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
        if (confirmChoice == JOptionPane.OK_OPTION) 
             {
                try{
                 double gamma=Double.parseDouble(gammaField.getText());
                int[][] imgFiltrer = Histogramme.rehaussement(imageNG.getMatrice(), Histogramme.creeCourbeTonaleGamma(gamma));
                imageNG.setMatrice(imgFiltrer);
                observer.setCImage(imageNG);
                System.out.println("end");
                try 
                {
                    int f_int[][] = imageNG.getMatrice();
                    histo = Histogramme.Histogramme256(f_int);
                } 
                catch (CImageNGException ex) 
                {
                    System.out.println("Erreur CImageNG : " + ex.getMessage());
                    return;
                }
                MakeHisto(histo,"Avec Gamma","Avec Gamme");
                }
                catch(Exception e)
                {
                 JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);   
                }
             }
    }//GEN-LAST:event_GammaItemActionPerformed

    private void NegatifItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegatifItemActionPerformed
       int[] histo;
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }

        MakeHisto(histo,"Avant Negatif","Avant Negatif");
        try{
        int[][] imgFiltrer = Histogramme.rehaussement(imageNG.getMatrice(), Histogramme.creeCourbeTonaleNegatif());
        imageNG.setMatrice(imgFiltrer);
        observer.setCImage(imageNG);
        System.out.println("end");
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }
        MakeHisto(histo,"Avec Negatif","Avec Negatif");
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);   
        }
    }//GEN-LAST:event_NegatifItemActionPerformed

    private void PrewittItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrewittItemActionPerformed
        if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
        JTextField dirField = new JTextField(5);
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Direction du filtre Prewitt :"));
        masquePanel.add(dirField);

         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
         {
            int dir = Integer.parseInt(dirField.getText());  
            int[][] imgFiltrer = ContoursLineaire.gradientPrewitt(imageNG.getMatrice(),dir);
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
         }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_PrewittItemActionPerformed

    private void SobelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobelItemActionPerformed
        if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
        JTextField dirField = new JTextField(5);
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Direction du filtre Sobel :"));
        masquePanel.add(dirField);

         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
         {
            int dir = Integer.parseInt(dirField.getText());  
            int[][] imgFiltrer = ContoursLineaire.gradientSobel(imageNG.getMatrice(),dir);
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
         }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SobelItemActionPerformed

    private void Laplace4ITemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Laplace4ITemActionPerformed
       if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            int[][] imgFiltrer = ContoursLineaire.laplacien4(imageNG.getMatrice());
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_Laplace4ITemActionPerformed

    private void Laplace8ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Laplace8ItemActionPerformed
    if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            int[][] imgFiltrer = ContoursLineaire.laplacien8(imageNG.getMatrice());
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Laplace8ItemActionPerformed

    private void gEroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gEroItemActionPerformed
       if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            int[][] imgFiltrer = ContoursNonLineaire.gradientErosion(imageNG.getMatrice());
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_gEroItemActionPerformed

    private void gDilItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gDilItemActionPerformed
       if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            int[][] imgFiltrer = ContoursNonLineaire.gradientDilatation(imageNG.getMatrice());
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_gDilItemActionPerformed

    private void gBeuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBeuItemActionPerformed
       if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            int[][] imgFiltrer = ContoursNonLineaire.gradientBeucher(imageNG.getMatrice());
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_gBeuItemActionPerformed

    private void LNLItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNLItemActionPerformed
    if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            int[][] imgFiltrer = ContoursNonLineaire.laplacienNonLineaire(imageNG.getMatrice());
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }       
    }//GEN-LAST:event_LNLItemActionPerformed

    private void SeuillageItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeuillageItemActionPerformed
       if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
        JTextField seuilleField = new JTextField(5);
        JPanel masquePanel = new JPanel();
        masquePanel.add(new JLabel("Seuille :"));
        masquePanel.add(seuilleField);

         int confirmChoice = JOptionPane.showConfirmDialog(this, masquePanel, "Donnée les valeur du masque:", JOptionPane.OK_CANCEL_OPTION);
         if (confirmChoice == JOptionPane.OK_OPTION) 
         {
            int seuille = Integer.parseInt(seuilleField.getText());  
            int[][] imgFiltrer = Seuillage.seuillageSimple(imageNG.getMatrice(),seuille);
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
            System.out.println("end");
         }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SeuillageItemActionPerformed

    private void SeuilAutoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeuilAutoItemActionPerformed
     if (imageNG == null) 
        {
            JOptionPane.showMessageDialog(this, "No grayscale image loaded.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            int[][] imgFiltrer = Seuillage.seuillageAutomatique(imageNG.getMatrice());
            imageNG.setMatrice(imgFiltrer);
            observer.setCImage(imageNG);
                System.out.println("end");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SeuilAutoItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IsilImageProcessing().setVisible(true);
            }
        });
    }

    public void ClicDetected(UnClicEvent e) 
    {
        if (jCheckBoxMenuItemDessinerPixel.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.setPixel(e.getX(),e.getY(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.setPixel(e.getX(),e.getY(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectLigneDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerLigne.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.DessineLigne(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.DessineLigne(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectRectDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerRectangle.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.DessineRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.DessineRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectCercleDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerCercle.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.DessineCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.DessineCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectCercleFillDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerCerclePlein.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.RemplitCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.RemplitCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    public void SelectRectFillDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerRectanglePlein.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.RemplitRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.RemplitRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }
    
    private void MakeHisto(int[] histo,String NomData, String nomChart)
    {
     // Cr�ation du dataset
        XYSeries serie = new XYSeries(NomData);
        for(int i=0 ; i<256 ; i++) serie.add(i,histo[i]);
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(serie);
        
        // Creation du chart
        JFreeChart chart = ChartFactory.createHistogram(nomChart,"Niveaux de gris","Nombre de pixels",dataset,PlotOrientation.VERTICAL,false,false,false);

        XYPlot plot = (XYPlot)chart.getXYPlot();
        ValueAxis axeX = plot.getDomainAxis();
        axeX.setRange(0,255);
        plot.setDomainAxis(axeX);
        
        // creation d'une frame
        ChartFrame frame = new ChartFrame("Histogramme de l'image",chart);
        frame.pack();
        frame.setVisible(true);  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AfficheItem2;
    private javax.swing.JMenuItem DilGeoItem;
    private javax.swing.JMenuItem DilatationItem;
    private javax.swing.JMenuItem EgalisationItem;
    private javax.swing.JMenuItem ErosionItem;
    private javax.swing.JMenuItem FermetureItem;
    private javax.swing.JMenuItem GammaItem;
    private javax.swing.JMenuItem LNLItem;
    private javax.swing.JMenuItem Laplace4ITem;
    private javax.swing.JMenuItem Laplace8Item;
    private javax.swing.JMenuItem MedItem;
    private javax.swing.JMenuItem MoyenneurItem;
    private javax.swing.JMenuItem NegatifItem;
    private javax.swing.JMenuItem OuvertureItem;
    private javax.swing.JMenuItem PrewittItem;
    private javax.swing.JMenuItem RecGeoItem;
    private javax.swing.JMenuItem SaturationItem;
    private javax.swing.JMenuItem SeuilAutoItem;
    private javax.swing.JMenuItem SeuillageItem;
    private javax.swing.JMenuItem SobelItem;
    private javax.swing.ButtonGroup buttonGroupDessiner;
    private javax.swing.JMenuItem gBeuItem;
    private javax.swing.JMenuItem gDilItem;
    private javax.swing.JMenuItem gEroItem;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerCercle;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerCerclePlein;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerLigne;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerPixel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerRectangle;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerRectanglePlein;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDessiner;
    private javax.swing.JMenu jMenuFourier;
    private javax.swing.JMenu jMenuFourierAfficher;
    private javax.swing.JMenu jMenuGlobal;
    private javax.swing.JMenu jMenuHistogramme;
    private javax.swing.JMenuItem jMenuHistogrammeAfficher;
    private javax.swing.JMenu jMenuImage;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCouleurPinceau;
    private javax.swing.JMenuItem jMenuItemEnregistrerSous;
    private javax.swing.JMenuItem jMenuItemFourierAfficherModule;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPartieImaginaire;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPartieReelle;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPhase;
    private javax.swing.JMenuItem jMenuItemHighPassButterworthFilter;
    private javax.swing.JMenuItem jMenuItemIdealHighPassFilter;
    private javax.swing.JMenuItem jMenuItemIdealLowPassFilter;
    private javax.swing.JMenuItem jMenuItemLowPassButterworthFilter;
    private javax.swing.JMenuItem jMenuItemNouvelleNG;
    private javax.swing.JMenuItem jMenuItemNouvelleRGB;
    private javax.swing.JMenuItem jMenuItemOuvrirNG;
    private javax.swing.JMenuItem jMenuItemOuvrirRGB;
    private javax.swing.JMenu jMenuLinearFiltering;
    private javax.swing.JMenu jMenuNouvelle;
    private javax.swing.JMenu jMenuOuvrir;
    private javax.swing.JMenuItem jMenuQuitter;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    
}
